name = "SnR Harpy Express"
author = "Slimeist"
version = "1.1.6-server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "563682f04b85098e34691780f5f264c75280c09dd7ae41573b831aa09f79c7f1"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
